/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    GoogleMap: typeof import('./src/components/GoogleMap.vue')['default']
    GoogleMapComponent: typeof import('./src/components/GoogleMapComponent.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarComponent: typeof import('./src/components/SidebarComponent.vue')['default']
  }
}
